x-REACT_APP_DOMAIN: &REACT_APP_DOMAIN
    REACT_APP_DOMAIN: <<<YOUR_DOMAIN>>>

x-MONGO_CONNECTION_STRING: &MONGO_CONNECTION_STRING
    MONGO_CONNECTION_STRING: <<<YOUR_MONGO_CONNECTION_STRING>>>

x-GROQ_API_KEY: &GROQ_API_KEY
    GROQ_API_KEY: <<<YOUR_GROQ_API_KEY>>>

x-GROQ_GPT_MODEL: &GROQ_GPT_MODEL
    GROQ_GPT_MODEL: <<<YOUR_MODEL_NAME>>>
####################################
version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      <<: [*REACT_APP_DOMAIN, *MONGO_CONNECTION_STRING, *GROQ_API_KEY, *GROQ_GPT_MODEL]
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      <<: *REACT_APP_DOMAIN
    depends_on:
      - backend

  tests:
    build:
      context: ./cypress
      dockerfile: Dockerfile
    depends_on:
      - backend
      - frontend
    environment:
      <<: *REACT_APP_DOMAIN
